### ISSUE TITLE
performance: use the cached routes?

### ISSUE THREAD

**Issue by dbu** [thormeier/breadcrumb-bundle#6]
this line triggers loading all routes on each request: https://github.com/thormeier/breadcrumb-bundle/blob/master/Provider/BreadcrumbProvider.php#L74

we should try to see if we can get that information from the route cache instead, to improve performance.

**Comment by thormeier** [comment]
Sounds reasonable. Perhaps build a breadcrumb cache as well?

**Comment by dbu** [comment]
could be an idea, yes. we could just scan the whole route collection
during warmup and write the breadcrumb tree to the cache to use that.

i would make that an optional feature. for dev mode, i would keep the
current behaviour, and some situations (e.g. custom router that can not
provide the collection) could make people want to not use that cache.

**Comment by thormeier** [comment]
@dbu After some discussion with @tobion, I made a few changes so it now uses the cache warmup to save raw breadcrumb info to the routing cache. Now the current tree will be available in `$request->get('_breadcrumbs')`, which doesn't cause the whole routing to get reloaded on every request.

Commit is 45dbe143216180a1074d9e2e63831d6fc777a291

Would be awesome if this could be tested, so we can release 2.1.0, since there are no BC breaks in this one.

**Comment by thormeier** [comment]
@dbu @tobion: Thank you very much for reviewing! Refactored it to use a compiler pass instead and fixed other stuff mentioned. Current commit is 658d6a3dde08f80b0ec2e8e48944cac6cc93dd7f

**Comment by dbu** [comment]
yay!
